version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: nsfe-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - nsfe-network

  neural-engine:
    build: .
    container_name: nsfe-engine
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - nsfe-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

networks:
  nsfe-network:
    driver: bridge
